// Personajes de ejemplo para /dev-preview (solo en desarrollo; nunca se guardan).
const base = {
  f_pronouns: "",
  f_transformation: "",
  f_languages: "Común",
  f_secondary_weapon: "",
  f_items: "[]",
  f_backpack: "[]",
  f_backpack_items: "[]",
  f_background_qa: "[]",
  f_connection_qa: "[]",
  hp_marked: "0",
  stress_marked: "0",
  hope_marked: "2",
  f_beastform: "",
  f_evolution_trait: "",
  f_conditions: "[]",
  f_journal: "[]",
  f_transformation_form_active: "",
  f_elemental_active: "",
  f_scars: "0",
  f_is_dead: "",
  f_domain_cards: "[]",
  f_projects: "[]",
  f_gold_units: "0",
  f_gold_tens: "1",
  f_gold_hundreds: "0",
  f_gold_thousands: "0",
};

const characters: Record<string, Record<string, string>> = {
  dev_druida: {
    ...base,
    f_name: "Kaelen Vox",
    f_class: "Druida",
    f_subclass: "Guardián de los Elementos",
    f_level: "1",
    f_proficiency: "1",
    f_ancestry: "Elfo",
    f_community: "Salvaje",
    f_transformation: "Hombre Lobo",
    t_agility: "1",
    t_strength: "-1",
    t_finesse: "0",
    t_instinct: "2",
    t_presence: "1",
    t_knowledge: "0",
    r_hp: "6",
    r_stress: "6",
    r_evasion: "10",
    f_primary_weapon: "Bastón",
    f_armor: "Armadura de cuero",
    armor_marked: "3",
    f_domain_cards: JSON.stringify(["Desatar el Caos", "Enredo Feroz"]),
    f_experiences: JSON.stringify([
      { text: "Guía de las tierras salvajes", bonus: 2 },
      { text: "Herbolario", bonus: 2 },
    ]),
  },
  dev_guerrero: {
    ...base,
    f_name: "Brunna Hierro",
    f_class: "Guerrero",
    f_subclass: "Llamado del Valiente",
    f_level: "5",
    f_proficiency: "3",
    f_ancestry: "Enano",
    f_community: "De las Cumbres",
    t_agility: "1",
    t_strength: "2",
    t_finesse: "0",
    t_instinct: "1",
    t_presence: "0",
    t_knowledge: "-1",
    r_hp: "6",
    r_stress: "6",
    r_evasion: "11",
    f_primary_weapon: "Espada larga avanzada",
    f_armor: "Cota de malla avanzada",
    armor_marked: "6",
    stress_marked: "5",
    f_experiences: JSON.stringify([{ text: "Veterana de asedios", bonus: 2 }]),
  },
  dev_mago: {
    ...base,
    f_name: "Ilia Tomo",
    f_class: "Mago",
    f_subclass: "Escuela del Conocimiento",
    f_level: "1",
    f_proficiency: "1",
    f_ancestry: "Humano",
    f_community: "Del Saber",
    t_agility: "0",
    t_strength: "-1",
    t_finesse: "0",
    t_instinct: "1",
    t_presence: "1",
    t_knowledge: "2",
    r_hp: "5",
    r_stress: "6",
    r_evasion: "11",
    f_primary_weapon: "Varita",
    f_armor: "",
    armor_marked: "0",
  },
};

export const DEV_SEED: Record<string, string> = {
  "player-name": "Probador",
  "character-index": JSON.stringify(Object.keys(characters)),
  ...Object.fromEntries(Object.entries(characters).map(([id, c]) => ["character:" + id, JSON.stringify(c)])),
};
